# cat services.yaml
version: '3'

services:
  gopro:
    build: .
    image: byrdapp/basic-server
    ports:
      - "443:443"
      - "8085:443"
      - "80:80"
    restart: always
    environment:
      - ENV=development
      - JWT_SECRET=givemeallthepros
    volumes:
      - "certs:/certs"
    command:
      - "-production=false"