# cat services.yaml
version: '3'

services:
  gopro:
    build: .
    image: byrdapp/basic-server
    ports:
      - "443:443"
      - "80:80"
    restart: always
    volumes:
        - "certs:/certs"
    environment:
      - ENV=development
    command:
      - "-host=gopro.byrd.news"

volumes:
  certs: